export const sider: Array<any> = [
  {
    siteId: 'TMG_INP',
    moduleIndex: 1,
    url: 'tmg_inp',
    type: '1',
    orderNum: 1,
    icon: 'WorkRegistration01',
    perms: 'TMG_INP',
    jaName: '就業入力サイト',
    enName: null,
    zhName: null,
    customerId: '01',
    companyId: '01',
    pageId: 'TMG_INP',
    secondMenuList: [
      {
        url: '/tmg_inp/TmgTimePunch',
        type: '3',
        orderNum: 2,
        icon: 'Stamping07',
        perms: 'TMG_INP_TmgTimePunch',
        jaName: '打刻',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgTimePunch',
        siteId: 'TMG_INP',
        menuIndex: 1
      },
      {
        url: '/tmg_inp/TmgResults',
        type: '3',
        orderNum: 3,
        icon: 'WorkRegistration01',
        perms: 'TMG_INP_TmgResults',
        jaName: '就業登録',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgResults',
        siteId: 'TMG_INP',
        menuIndex: 2
      },
      {
        url: '/tmg_inp/TmgNotification',
        type: '3',
        orderNum: 4,
        icon: 'VacationApplication08',
        perms: 'TMG_INP_TmgNotification',
        jaName: '休暇・休業申請',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgNotification',
        siteId: 'TMG_INP',
        menuIndex: 3
      },
      {
        url: '/tmg_inp/TmgHomeWork',
        type: '3',
        orderNum: 5,
        icon: 'workfromhome',
        perms: 'TMG_INP_TmgHomeWork',
        jaName: '在宅勤務',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgHomeWork',
        siteId: 'TMG_INP',
        menuIndex: 4
      },
      {
        url: '/tmg_inp/AttendanceBook',
        type: '3',
        orderNum: 6,
        icon: 'EmployeeRecord15',
        perms: 'TMG_INP_AttendanceBook',
        jaName: '出勤簿',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'AttendanceBook',
        siteId: 'TMG_INP',
        menuIndex: 5
      },
      {
        url: '/tmg_inp/TmgScheduleCheck',
        type: '3',
        orderNum: 7,
        icon: 'ScheduleConfirmation09',
        perms: 'TMG_INP_TmgScheduleCheck',
        jaName: '予定確認',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgScheduleCheck',
        siteId: 'TMG_INP',
        menuIndex: 6
      },
      {
        url: '/tmg_inp/NoticeBoard',
        type: '3',
        orderNum: 8,
        icon: 'DisplayBoard42',
        perms: 'TMG_INP_NoticeBoard',
        jaName: '掲示板',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'NoticeBoard',
        siteId: 'TMG_INP',
        menuIndex: 7
      },
      {
        url: '/tmg_inp/TmgTaktTime',
        type: '3',
        orderNum: 9,
        icon: 'monthworktime',
        perms: 'TMG_INP_TmgTaktTime',
        jaName: '月次工数実績',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgTaktTime',
        siteId: 'TMG_INP',
        menuIndex: 8
      }
    ]
  },
  {
    siteId: 'TMG_PERM',
    moduleIndex: 4,
    url: 'tmg_perm',
    type: '1',
    orderNum: 10,
    icon: 'WorkApproval02',
    perms: 'TMG_PERM',
    jaName: '就業承認サイト',
    enName: null,
    zhName: null,
    customerId: '01',
    companyId: '01',
    pageId: 'TMG_PERM',
    secondMenuList: [
      {
        url: '/tmg_perm/PermStatList',
        type: '3',
        orderNum: 11,
        icon: 'ApprovalStatusList11',
        perms: 'TMG_PERM_PermStatList',
        jaName: '承認状況一覧',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'PermStatList',
        siteId: 'TMG_PERM',
        menuIndex: 1
      },
      {
        url: '/tmg_perm/TmgResults',
        type: '3',
        orderNum: 12,
        icon: 'WorkApproval02',
        perms: 'TMG_PERM_TmgResults',
        jaName: '就業承認',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgResults',
        siteId: 'TMG_PERM',
        menuIndex: 2
      },
      {
        url: '/tmg_perm/OvertimeInstruct',
        type: '3',
        orderNum: 13,
        icon: 'OvertimeOrders12',
        perms: 'TMG_PERM_OvertimeInstruct',
        jaName: '超過勤務命令',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'OvertimeInstruct',
        siteId: 'TMG_PERM',
        menuIndex: 3
      },
      {
        url: '/tmg_perm/TmgNotification',
        type: '3',
        orderNum: 14,
        icon: 'VacationConfirmation29',
        perms: 'TMG_PERM_TmgNotification',
        jaName: '休暇・休業承認',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgNotification',
        siteId: 'TMG_PERM',
        menuIndex: 4
      },
      {
        url: '/tmg_perm/TmgSchedule',
        type: '3',
        orderNum: 15,
        icon: 'CreateSchedule13',
        perms: 'TMG_PERM_TmgSchedule',
        jaName: '予定作成',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgSchedule',
        siteId: 'TMG_PERM',
        menuIndex: 5
      },
      {
        url: '/tmg_perm/DeptStatList',
        type: '3',
        orderNum: 16,
        icon: 'UnitStatistics14',
        perms: 'TMG_PERM_DeptStatList',
        jaName: '部署別統計情報',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'DeptStatList',
        siteId: 'TMG_PERM',
        menuIndex: 6
      },
      {
        url: '/tmg_perm/EvaluaterSetting',
        type: '3',
        orderNum: 17,
        icon: 'PermissionSettings16',
        perms: 'TMG_PERM_EvaluaterSetting',
        jaName: '権限設定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'EvaluaterSetting',
        siteId: 'TMG_PERM',
        menuIndex: 7
      },
      {
        url: '/tmg_perm/AttendanceBook',
        type: '3',
        orderNum: 18,
        icon: 'EmployeeRecord15',
        perms: 'TMG_PERM_AttendanceBook',
        jaName: '出勤簿',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'AttendanceBook',
        siteId: 'TMG_PERM',
        menuIndex: 8
      },
      {
        url: '/tmg_perm/PatternSetting',
        type: '3',
        orderNum: 19,
        icon: 'WorkManage03',
        perms: 'TMG_PERM_PatternSetting',
        jaName: '勤務パターン設定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'PatternSetting',
        siteId: 'TMG_PERM',
        menuIndex: 9
      },
      {
        url: '/tmg_perm/TmgAcquired5DaysHoliday',
        type: '3',
        orderNum: 20,
        icon: 'FiveDaysPaid28',
        perms: 'TMG_PERM_TmgAcquired5DaysHoliday',
        jaName: '年5日時季指定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgAcquired5DaysHoliday',
        siteId: 'TMG_PERM',
        menuIndex: 10
      },
      {
        url: '/tmg_perm/TmgHomeWork',
        type: '3',
        orderNum: 21,
        icon: 'workfromhome',
        perms: 'TMG_PERM_TmgHomeWork',
        jaName: '在宅勤務',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgHomeWork',
        siteId: 'TMG_PERM',
        menuIndex: 11
      },
      {
        url: '/tmg_perm/TmgLiquidationPeriod',
        type: '3',
        orderNum: 22,
        icon: 'liquidation',
        perms: 'TMG_PERM_TmgLiquidationPeriod',
        jaName: '精算期間',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgLiquidationPeriod',
        siteId: 'TMG_PERM',
        menuIndex: 12
      },
      {
        url: '/tmg_perm/TmgGroupSchedule',
        type: '3',
        orderNum: 23,
        icon: 'deptschedule',
        perms: 'TMG_PERM_TmgGroupSchedule',
        jaName: '部局別勤務予定情報',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgGroupSchedule',
        siteId: 'TMG_PERM',
        menuIndex: 13
      },
      {
        url: '/tmg_perm/TmgTaktTime',
        type: '3',
        orderNum: 24,
        icon: 'monthworktime',
        perms: 'TMG_PERM_TmgTaktTime',
        jaName: '月次工数実績',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgTaktTime',
        siteId: 'TMG_PERM',
        menuIndex: 14
      }
    ]
  },
  {
    siteId: 'TMG_ADMIN',
    moduleIndex: 3,
    url: 'tmg_admin',
    type: '1',
    orderNum: 25,
    icon: 'WorkManage03',
    perms: 'TMG_ADMIN',
    jaName: '就業管理サイト',
    enName: null,
    zhName: null,
    customerId: '01',
    companyId: '01',
    pageId: 'TMG_ADMIN',
    secondMenuList: [
      {
        url: '/tmg_admin/PermStatList',
        type: '3',
        orderNum: 26,
        icon: 'ApprovalStatusList11',
        perms: 'TMG_ADMIN_PermStatList',
        jaName: '承認状況一覧',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'PermStatList',
        siteId: 'TMG_ADMIN',
        menuIndex: 1
      },
      {
        url: '/tmg_admin/TmgResults',
        type: '3',
        orderNum: 27,
        icon: 'WorkApproval02',
        perms: 'TMG_ADMIN_TmgResults',
        jaName: '就業承認',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgResults',
        siteId: 'TMG_ADMIN',
        menuIndex: 2
      },
      {
        url: '/tmg_admin/OvertimeInstruct',
        type: '3',
        orderNum: 28,
        icon: 'OvertimeOrders12',
        perms: 'TMG_ADMIN_OvertimeInstruct',
        jaName: '超過勤務命令',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'OvertimeInstruct',
        siteId: 'TMG_ADMIN',
        menuIndex: 3
      },
      {
        url: '/tmg_admin/TmgNotification',
        type: '3',
        orderNum: 29,
        icon: 'VacationConfirmation29',
        perms: 'TMG_ADMIN_TmgNotification',
        jaName: '休暇・休業承認',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgNotification',
        siteId: 'TMG_ADMIN',
        menuIndex: 4
      },
      {
        url: '/tmg_admin/TmgSchedule',
        type: '3',
        orderNum: 30,
        icon: 'CreateSchedule13',
        perms: 'TMG_ADMIN_TmgSchedule',
        jaName: '予定作成',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgSchedule',
        siteId: 'TMG_ADMIN',
        menuIndex: 5
      },
      {
        url: '/tmg_admin/AttendanceBook',
        type: '3',
        orderNum: 31,
        icon: 'EmployeeRecord15',
        perms: 'TMG_ADMIN_AttendanceBook',
        jaName: '出勤簿',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'AttendanceBook',
        siteId: 'TMG_ADMIN',
        menuIndex: 6
      },
      {
        url: '/tmg_admin/DeptStatList',
        type: '3',
        orderNum: 32,
        icon: 'UnitStatistics14',
        perms: 'TMG_ADMIN_DeptStatList',
        jaName: '部署別統計情報',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'DeptStatList',
        siteId: 'TMG_ADMIN',
        menuIndex: 7
      },
      {
        url: '/tmg_admin/EvaluaterSetting',
        type: '3',
        orderNum: 33,
        icon: 'PermissionSettings16',
        perms: 'TMG_ADMIN_EvaluaterSetting',
        jaName: '権限設定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'EvaluaterSetting',
        siteId: 'TMG_ADMIN',
        menuIndex: 8
      },
      {
        url: '/tmg_admin/PaidHoliday',
        type: '3',
        orderNum: 34,
        icon: 'VacationYearManage26',
        perms: 'TMG_ADMIN_PaidHoliday',
        jaName: '年次休暇管理',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'PaidHoliday',
        siteId: 'TMG_ADMIN',
        menuIndex: 9
      },
      {
        url: '/tmg_admin/MonthlyOutput',
        type: '3',
        orderNum: 35,
        icon: 'CreateMonthlySummary17',
        perms: 'TMG_ADMIN_MonthlyOutput',
        jaName: '月次集計',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'MonthlyOutput',
        siteId: 'TMG_ADMIN',
        menuIndex: 10
      },
      {
        url: '/tmg_admin/PatternSetting',
        type: '3',
        orderNum: 36,
        icon: 'WorkManage03',
        perms: 'TMG_ADMIN_PatternSetting',
        jaName: '勤務パターン設定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'PatternSetting',
        siteId: 'TMG_ADMIN',
        menuIndex: 11
      },
      {
        url: '/tmg_admin/Calendar',
        type: '3',
        orderNum: 37,
        icon: 'CalendarEditing19',
        perms: 'TMG_ADMIN_Calendar',
        jaName: 'カレンダー編集',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'Calendar',
        siteId: 'TMG_ADMIN',
        menuIndex: 12
      },
      {
        url: '/tmg_admin/EmpAttrSetting',
        type: '3',
        orderNum: 38,
        icon: 'PersonalAttributeSettings20',
        perms: 'TMG_ADMIN_EmpAttrSetting',
        jaName: '個人属性設定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'EmpAttrSetting',
        siteId: 'TMG_ADMIN',
        menuIndex: 13
      },
      {
        url: '/tmg_admin/TmgBulkNotification',
        type: '3',
        orderNum: 39,
        icon: 'VacationLumpRegistration27',
        perms: 'TMG_ADMIN_TmgBulkNotification',
        jaName: '休暇一括登録',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgBulkNotification',
        siteId: 'TMG_ADMIN',
        menuIndex: 14
      },
      {
        url: '/tmg_admin/TmgLedger',
        type: '3',
        orderNum: 40,
        icon: 'ReportOutput21',
        perms: 'TMG_ADMIN_TmgLedger',
        jaName: '帳票出力',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgLedger',
        siteId: 'TMG_ADMIN',
        menuIndex: 15
      },
      {
        url: '/tmg_admin/TmgIfSimulation',
        type: '3',
        orderNum: 41,
        icon: 'LinkageMasterSettings22',
        perms: 'TMG_ADMIN_TmgIfSimulation',
        jaName: '連携対象者設定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgIfSimulation',
        siteId: 'TMG_ADMIN',
        menuIndex: 16
      },
      {
        url: '/tmg_admin/TmgAcquired5DaysHoliday',
        type: '3',
        orderNum: 42,
        icon: 'FiveDaysPaid28',
        perms: 'TMG_ADMIN_TmgAcquired5DaysHoliday',
        jaName: '年5日時季指定',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgAcquired5DaysHoliday',
        siteId: 'TMG_ADMIN',
        menuIndex: 17
      },
      {
        url: '/tmg_admin/TmgHomeWork',
        type: '3',
        orderNum: 43,
        icon: 'workfromhome',
        perms: 'TMG_ADMIN_TmgHomeWork',
        jaName: '在宅勤務',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgHomeWork',
        siteId: 'TMG_ADMIN',
        menuIndex: 18
      },
      {
        url: '/tmg_admin/TmgLiquidationPeriod',
        type: '3',
        orderNum: 44,
        icon: 'liquidation',
        perms: 'TMG_ADMIN_TmgLiquidationPeriod',
        jaName: '精算期間',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgLiquidationPeriod',
        siteId: 'TMG_ADMIN',
        menuIndex: 19
      },
      {
        url: '/tmg_admin/CsvInput',
        type: '3',
        orderNum: 45,
        icon: 'VacationLumpRegistration27',
        perms: 'TMG_ADMIN_CsvInput',
        jaName: 'CSV取込',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'CsvInput',
        siteId: 'TMG_ADMIN',
        menuIndex: 20
      },
      {
        url: '/tmg_admin/TmgTaktTime',
        type: '3',
        orderNum: 46,
        icon: 'monthworktime',
        perms: 'TMG_ADMIN_TmgTaktTime',
        jaName: '月次工数実績',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgTaktTime',
        siteId: 'TMG_ADMIN',
        menuIndex: 21
      },
      {
        url: '/tmg_admin/TmgGroupSchedule',
        type: '3',
        orderNum: 47,
        icon: 'deptschedule',
        perms: 'TMG_ADMIN_TmgGroupSchedule',
        jaName: '局別勤務予定情報',
        enName: null,
        zhName: null,
        customerId: '01',
        companyId: '01',
        pageId: 'TmgGroupSchedule',
        siteId: 'TMG_ADMIN',
        menuIndex: 22
      }
    ]
  }
]
